name: luton_airport
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  args: ^2.0.0
  getwidget: ^1.1.0
  url_launcher: ^5.7.10
  flutter_markdown: ^0.6.1
  path: ^1.6.2
  http: ^0.12.0
  html: ^0.15.0
  html2md: ^1.0.1
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  pedantic: ^1.9.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/data/help.json
    - assets/data/dests.json
    - assets/data/flights.json
    - assets/data/retail.json
    - assets/images/logo.png
    - assets/data/images/benugo-listing-image-800x470.jpg
    - assets/data/images/Benugo.png
    - assets/data/images/auntieannes-listing-image-800x470.jpg
    - assets/data/images/Auntie-Anne's.png
    - assets/data/images/burgerking-listing-image-800x470-2.jpg
    - assets/data/images/burger-king.jpg
    - assets/data/images/costa-listing-image-800x470.jpg
    - assets/data/images/costa.jpg
    - assets/data/images/fattorie-listing-image-800x470.jpg
    - assets/data/images/fattorie-Garofalo.png
    - assets/data/images/enrique-tomas-listing-image-800x470.jpg
    - assets/data/images/enrique-tomas.png
    - assets/data/images/friska-listing-image-800x470.jpg
    - assets/data/images/Friska.png
    - assets/data/images/pret-idl-listing-image-800x470.jpg
    - assets/data/images/pret.png
    - assets/data/images/krispy-kreme-listing-image-800x470.jpg
    - assets/data/images/Krispy-Kreme.png
    - assets/data/images/wasabi-listing-image-800x470.jpg
    - assets/data/images/Wasabi.png
    - assets/data/images/pret-gate7-listing-image-800x470.jpg
    - assets/data/images/pret-listing-image-800x470.jpg
    - assets/data/images/pret.jpg
    - assets/data/images/starbucks-listing-image-800x470.jpg
    - assets/data/images/Starbucks.png
    - assets/data/images/starbucks2-listing-image-800x470.jpg
    - assets/data/images/starbucks.jpg
    - assets/data/images/frankies-listing-image-800x470.jpg
    - assets/data/images/Frankie-and-benny's.png
    - assets/data/images/smithfield-listing-image-800x470.jpg
    - assets/data/images/smithfield.png
    - assets/data/images/aelia-listing-image-800x470.jpg
    - assets/data/images/duty-free.png
    - assets/data/images/ice-listing-image-800x470.jpg
    - assets/data/images/ice-airside.png
    - assets/data/images/accessorize-listing-image-800x470.jpg
    - assets/data/images/Accessorize.png
    - assets/data/images/gb-listing-image-800x470.jpg
    - assets/data/images/glorious-britain.png
    - assets/data/images/mands-listing-image-800x470.jpg
    - assets/data/images/m-s.jpg
    - assets/data/images/dixons-listing-image-800x470.jpg
    - assets/data/images/Dixons.png
    - assets/data/images/hamleys-listing-image-800x470.jpg
    - assets/data/images/hamley's.png
    - assets/data/images/boots-listing-image-800x470.jpg
    - assets/data/images/boots.png
    - assets/data/images/ice-listing-image-800x470.jpg
    - assets/data/images/ice.jpg
    - assets/data/images/aelia-landside-listing-image-800x470.jpg
    - assets/data/images/aelia.jpg
    - assets/data/images/ice-listing-image-800x470.jpg
    - assets/data/images/whsmiths-landside-listing-image-800x470.jpg
    - assets/data/images/whsmith.jpg
    - assets/data/images/whsmiths-airside2-listing-image-800x470.jpg
    - assets/data/images/WHSmith.png
    - assets/data/images/boss-listing-image-800x470.jpg
    - assets/data/images/hugo-boss.png
    - assets/data/images/rituals-listing-image-800x470.jpg
    - assets/data/images/Rituals.png
    - assets/data/images/collection-listing-image-800x470.jpg
    - assets/data/images/collection.png
    - assets/data/images/fiorelli-listing-image-800x470.jpg
    - assets/data/images/Fiorelli.png
    - assets/data/images/kurt-girger-listing-image-800x470.jpg
    - assets/data/images/kurt-geiger.png
    - assets/data/images/next-brand-image-690x453.jpg
    - assets/data/images/next.png
    - assets/data/images/oliver-bonas-listing-image-800x470.jpg
    - assets/data/images/Oliver-Bonas.png
    - assets/data/images/JD-listing-image-800x470.jpg
    - assets/data/images/JD.png
    - assets/data/images/ted-listing-image-800x470.jpg
    - assets/data/images/ted-baker.png
    - assets/data/images/sunglasshut-listing-image-800x470.jpg
    - assets/data/images/sunglasses-hut.png
    - assets/data/images/vics-sec-listing-image-800x470.jpg
    - assets/data/images/Victoria's-secret.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
